name: Build and Inspect React App

on:
  push:
    branches:
      - main

jobs:
  build: #Freiw√§hlbarer Name
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the App
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm i